### ISSUE TITLE
root password

### ISSUE THREAD

**Issue by tobeorla** [alekzonder/docker-puppeteer#25]
I'm having connectivity issues (only the first request worked, then i get `could not resolve` error) and i would like to do things like `service networking restart` inside the machine but i need the root password for that.
¿Could you give it?

**O.S**: Windows 10
**Command**:
```bash
 docker run --net=host --dns 8.8.8.8 --dns 8.8.4.4 --rm -v ~/Phpstorm/test:/app/ alekzonder/puppeteer:latest node index.js
```

`Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r571375`

**Comment by isakatirci** [comment]
what is root password?
