### ISSUE TITLE
Can't install additional software

### ISSUE THREAD

**Issue by Jagget** [alekzonder/docker-puppeteer#42]
Using it as GitLab CI image. Need PIP3 library for deployment

```
image: alekzonder/puppeteer:latest

services:
  - docker:dind
```

Getting an error:

```shell
$ apt-get install python3-pip -y
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
```

**Comment by rudolfbyker** [comment]
This is probably because of `rm -rf /var/lib/apt/lists/*` at https://github.com/alekzonder/docker-puppeteer/blob/35983d4a2941df824054eb123e411fa88b38988b/Dockerfile#L12
