### ISSUE TITLE
Prevent zombie chrome processes with dumb-init, s6, or similar

### ISSUE THREAD

**Issue by grayside** [alekzonder/docker-puppeteer#5]
The [Official Puppeteer Docker guidance](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker) recommends using dumb-init as an entrypoint to prevent chrome from spinning up and being unable to terminate processes. Adding it here will make the image more robust.

**Comment by alekzonder** [comment]
fixed
